### ISSUE TITLE
Bug in conserved moiety translation

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#357]
Run

 following script:

import tellurium as te
r = te.loads('model_niels.xml')
r.conservedMoietyAnalysis = True

using the model in the attachment (rename extension to xml) causes a runtime error:

error converting document to conserved moieties, at ??0ModelGeneratorContext@rrllvm@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@I@Z

I think this is quite urgent. 

Herbert

**Comment by matthiaskoenig** [comment]
The latest changes in the codebase create problems on linux. I put this here, because the changes are related to the conserved moiety problem. When running the roadrunner test suite it fails with

```
Check [Set Steady State Selection List]      ConservedMoietyConverter::setDocument
Error: ConservedMoietyConverter resultDoc->setModel(mModel) failed: 
The SBML Version within the SBML Level associated with the object does not match the Version of the parent object. This error can happen when an SBML component such as a species or compartment object is created outside of a model and a calling program then attempts to add the object to a model that has a different SBML Level+Version combination. 
Traceback (most recent call last):
  File "../tests/roadrunner_test.py", line 14, in <module>
    roadrunner.testing.runTester()
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/testing/tester.py", line 1260, in runTester
    func(rrInstance, testId)
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/testing/tester.py", line 468, in checkSetSteadyStateSelectionList
    rrInstance.conservedMoietyAnalysis = True
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/roadrunner.py", line 2554, in <lambda>
    __setattr__ = lambda self, name, value: _swig_setattr(self, RoadRunner, name, value)
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/roadrunner.py", line 61, in _swig_setattr
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/roadrunner.py", line 50, in _swig_setattr_nondynamic
    return method(self, value)
  File "/usr/local/lib/python2.7/dist-packages/libroadrunner-1.4.15-py2.7.egg/roadrunner/roadrunner.py", line 3128, in _setConservedMoietyAnalysis
    return _roadrunner.RoadRunner__setConservedMoietyAnalysis(self, value)
RuntimeError: error converting document to conserved moieties, at rrllvm::ModelGeneratorContext::ModelGeneratorContext(const string&, unsigned int)
```
The following changes create the problem
```
From https://github.com/sys-bio/roadrunner
   aef6b5b..6a7130a  develop    -> origin/develop
 * [new branch]      matthiaskoenig-patch-1 -> origin/matthiaskoenig-patch-1
 * [new tag]         1.4.15     -> 1.4.15
Updating aef6b5b..6a7130a
Fast-forward
 CMakeLists.txt                                   | 2 +-
 source/conservation/ConservedMoietyConverter.cpp | 4 ++++
 wrappers/Python/CMakeLists.txt                   | 7 +++++--
 3 files changed, 10 insertions(+), 3 deletions(-)
Already on 'develop'
M	cmake/FindNumPy.cmake
M	data/simpleNoise-MissingData.dat
M	data/simpleNoise.dat
M	data/simpleNoiseWeights.dat
M	examples/CMakeLists.txt
M	examples/create_uuid/main.cpp
M	examples/events/feedback.xml
M	examples/load_model_dll/CMakeLists.txt
M	examples/load_model_dll/Readme.txt
M	examples/load_model_dll/main.cpp
M	examples/one_rr/CMakeLists.txt
M	examples/one_rr/Readme.txt
M	examples/one_rr/main.cpp
M	examples/two_rrs/CMakeLists.txt
M	examples/two_rrs/Readme.txt
M	examples/two_rrs/main.cpp
M	models/BorisEJB.xml
M	models/CMakeLists.txt
M	models/MinimizationTest_A.xml
M	models/bug.xml
M	models/sbml_test_0001.xml
M	models/simple.xml
M	models/squareWaveModel.xml
M	models/ss_SimpleConservedCycle.xml
M	models/ss_TurnOnConservationAnalysis.xml
M	models/ss_threeSpecies.xml
M	models/ss_threestep.xml
M	models/test_models/CMakeLists.txt
M	models/test_models/TestModel_1.xml
M	models/test_models/reference_data/CMakeLists.txt
M	models/test_models/reference_data/TestModel_1.dat
M	rr_support/CMakeLists.txt
M	rr_support/bcc.cfg
M	rr_support/rrSupport.c
M	source/llvm_testing/run_cpp_tests.bat
M	source/testing/CMakeLists.txt
M	source/testing/run_cpp_tests.bat
M	source/testing/run_cpp_tests.sh
Your branch is up-to-date with 'origin/develop'.
*commit*
6a7130a86dc3dc0b03c5c7f17f10fc1dccdf16ac
```

The system libsbml installation is not necessarily the libsbml installation packed in roadrunner!
I need the latest libsbml develop version to work with my models. This was no issue until now.

the best
Matthias

**Comment by hsauro** [comment]
Kyle, I thought we had an automated test suite to prevent this?

Herbert

**Comment by 0u812** [comment]
I think the changes I just pushed should fix this. I will look into the test suite.

**Comment by matthiaskoenig** [comment]
yes, works now
