### ISSUE TITLE
Issue with Binary Wheel

### ISSUE THREAD

**Issue by 0u812** [sys-bio/roadrunner#399]
The wheel seems not to work on some Linux systems. Examples include the readthedocs builder and Shaik's Docker container.

**Comment by matthiaskoenig** [comment]
I experienced the same.
Everything works nice on ubuntu 16.04 for me, but 2-3 days ago the travis build environment was updated and since than the wheels are not building correctly on travis for me (part of the update was clang, so I think it has something to do with that).
For me it was antimony which did not work.

**Comment by matthiaskoenig** [comment]
I can see the issues in the travis reports. Hope it helps for debuging.
You should be able to see these at
https://travis-ci.org/sys-bio/tellurium
In python 2.7 I get the roadrunner import error
```
======================================================================

ERROR: Failure: ImportError (No module named _roadrunner)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/home/travis/build/sys-bio/tellurium/tellurium/__init__.py", line 8, in <module>

    from .tellurium import (

  File "/home/travis/build/sys-bio/tellurium/tellurium/tellurium.py", line 115, in <module>

    import roadrunner

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/roadrunner/__init__.py", line 10, in <module>

    import roadrunner

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/roadrunner/roadrunner.py", line 23, in <module>

    _roadrunner = swig_import_helper()

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/roadrunner/roadrunner.py", line 22, in swig_import_helper

    return importlib.import_module('_roadrunner')

  File "/opt/python/2.7.13/lib/python2.7/importlib/__init__.py", line 37, in import_module

    __import__(name)

ImportError: No module named _roadrunner
```
and also experience this locally when trying to build tellurium with tox in a virtualenv building against python 2.7.

In python 3.5 and 3.6 I get on travis 
```
/home/travis/.travis/job_stages: line 57:  4218 Segmentation fault      (core dumped) nosetests
```
Locally on Ubuntu 16.04 LTS everything works.

**Comment by 0u812** [comment]
Fixed now. API autodoc on readthedocs works. Travis build still fails, but appears to be due to tests not passing, not binary wheel issues.

**Comment by matthiaskoenig** [comment]
Thanks for this. Can work on the tests now.
