### ISSUE TITLE
roadrunner.testing.getRoadRunner("feedback.xml") not working

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#400]
Before it was possible to get the testmodels in roadrunner via
```
roadrunner.testing.getRoadRunner("feedback.xml")
```
This is not working any more. Below code to reproduce, i.e. install latest roadrunner in virtualenv and try to load the feedback model.
Mentioned this shortly during Harmony, but forgot to create a bug report.
Best M

```
mkoenig@prime1:~/git/tellurium$ mkvirtualenv roadrunner
Using base prefix '/usr'
New python executable in /home/mkoenig/envs/roadrunner/bin/python3
Also creating executable in /home/mkoenig/envs/roadrunner/bin/python
Installing setuptools, pip, wheel...done.
virtualenvwrapper.user_scripts creating /home/mkoenig/envs/roadrunner/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/mkoenig/envs/roadrunner/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/mkoenig/envs/roadrunner/bin/preactivate
virtualenvwrapper.user_scripts creating /home/mkoenig/envs/roadrunner/bin/postactivate
virtualenvwrapper.user_scripts creating /home/mkoenig/envs/roadrunner/bin/get_env_details

(roadrunner) mkoenig@prime1:~/git/tellurium$ pip install libroadrunner
Collecting libroadrunner
  Using cached libroadrunner-1.4.18-cp35-cp35m-manylinux1_x86_64.whl
Collecting matplotlib>=1.5 (from libroadrunner)
  Using cached matplotlib-2.0.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting numpy>=1.12 (from libroadrunner)
  Using cached numpy-1.13.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=1.5->libroadrunner)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib>=1.5->libroadrunner)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib>=1.5->libroadrunner)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib>=1.5->libroadrunner)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib>=1.5->libroadrunner)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, cycler, numpy, python-dateutil, pyparsing, pytz, matplotlib, libroadrunner
Successfully installed cycler-0.10.0 libroadrunner-1.4.18 matplotlib-2.0.2 numpy-1.13.1 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 six-1.10.0
(roadrunner) mkoenig@prime1:~/git/tellurium$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import roadrunner.testing

>>> roadrunner.testing.getRoadRunner("feedback.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mkoenig/envs/roadrunner/lib/python3.5/site-packages/roadrunner/testing/testfiles.py", line 38, in getRoadRunner
    r.load(data)
  File "/home/mkoenig/envs/roadrunner/lib/python3.5/site-packages/roadrunner/roadrunner.py", line 3466, in load
    self._load(*args)
  File "/home/mkoenig/envs/roadrunner/lib/python3.5/site-packages/roadrunner/roadrunner.py", line 2768, in _load
    return _roadrunner.RoadRunner__load(self, uriOrSBML, options)
NotImplementedError: Wrong number or type of arguments for overloaded function 'RoadRunner__load'.
  Possible C/C++ prototypes are:
    rr::RoadRunner::load(std::string const &,rr::Dictionary const *)
    rr::RoadRunner::load(std::string const &)
```

**Comment by kirichoi** [comment]
Fixed by commit https://github.com/sys-bio/roadrunner/commit/3a8d9799266a42bca5814de9ac19db05b5a9d5da
