### ISSUE TITLE
'Unknown exception' issued when parameter is not initialized

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#657]
Try this model

r = te.loada("""
   J1: S1 -> S2; k0 + k1*S1
   J2: S2 -> S3; k2*S2
   
   S1 = 1; S2 = 0; S3 = 0; 
   k1 = 0; k2 = 0; 
   k1 = 0.45; k2 = 0.15;
""")

and you get  (I presume its because k0 hasn't been initialized,) Is this related to previous questions you've ben asking? Perhaps it's fixed in the code but not yet released?

Traceback (most recent call last):

  File "D:\Documents\Summer2020Course\fitting_2_step_A.py", line 30, in <module>
    """)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\tellurium.py", line 517, in loada
    return loadAntimonyModel(ant)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\tellurium.py", line 534, in loadAntimonyModel
    return roadrunner.RoadRunner(sbml)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\roadrunner\extended_roadrunner.py", line 16, in __init__
    super(ExtendedRoadRunner, self).__init__(*args, **kwargs)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\roadrunner\roadrunner.py", line 3768, in _new_init
    RoadRunner._swig_init(self, *args)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\roadrunner\roadrunner.py", line 2524, in __init__
    this = _roadrunner.new_RoadRunner(*args)

RuntimeError: Unknown exception

**Comment by evilnose** [comment]
Yes, I think it's because `k0` is not initialized. I've fixed the error message in [this](https://github.com/sys-bio/roadrunner/pull/655) open PR, and once it's merged the error should say

"RuntimeError: Global parameter 'k0' missing value and missing init assignment and assignment rule!"

**Comment by hsauro** [comment]
That’s better.

**Comment by evilnose** [comment]
The mentioned PR was merged.
