### ISSUE TITLE
AttrtibuteError in tellurium nullspace call 

### ISSUE THREAD

**Issue by hsauro** [sys-bio/roadrunner#683]
Calling nullspace on telluirum crashes, preosumable the numpy call should be 

numpy.linalg.svd  and not numpy.svd (confirmed by changing my local copy)

import tellurium as te
import roadrunner

r = te.loada("""
    A -> B; v;
    2 B -> A; v;
    
    v = 1;
""")

te.utils.matrix.nullspace (r.getFullStoichiometryMatrix())

Traceback (most recent call last):

  File "<ipython-input-85-d7d80ad2d6ca>", line 1, in <module>
    te.utils.matrix.nullspace (r.getFullStoichiometryMatrix())

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\tellurium\utils\matrix.py", line 84, in nullspace
    u, s, vh = np.svd(A)

  File "C:\Tellurium-Winpython-3.7\python-3.7.7.amd64\lib\site-packages\numpy\__init__.py", line 215, in __getattr__
    "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'svd'

**Comment by luciansmith** [comment]
Fixed in Tellurium.
