### ISSUE TITLE
Not possible to set initialValues on species with `boundaryCondition=True`

### ISSUE THREAD

**Issue by matthiaskoenig** [sys-bio/roadrunner#711]
I want to set the initialValue on a species with `boundaryCondition=True`. This gives an error in roadrunner.
In the example I have one species A1 with `boundaryCondition=False` and a species A2 with`boundaryCondition=True`
[boundary_condition.zip](https://github.com/sys-bio/roadrunner/files/5516719/boundary_condition.zip)
```
import roadrunner

# Loading model and simulating
model = roadrunner.RoadRunner("boundary_condition.xml")  # type: roadrunner.ExecutableModel
model.selections = ["time", "A1", "A2", "[A1]", "[A2]"]

# setting initial value on species with "boundaryCondition=False"
model["init(A1)"] = 10.0
# setting initial value on species with "boundaryCondition=True" (results in error)
model["init(A2)"] = 10.0
```
Returns
```
Traceback (most recent call last):
  File "/home/mkoenig/git/sbmlutils/src/sbmlutils/examples/models/boundary_condition_2/results/initial_assignment_rr.py", line 10, in <module>
    model["init(A2)"] = 10.0
  File "/home/mkoenig/envs/sbmlutils/lib/python3.8/site-packages/roadrunner/roadrunner.py", line 3619, in __setitem__
    return _roadrunner.RoadRunner___setitem__(self, id, value)
RuntimeError: Invalid Id for initial value: 'init(A2)'
```
This seems to be a bug. How can I set the initialValue on such a species?
The `init` syntax should be consistent for all species.

I can set the value directly without init (but this requires to know that the species is a boundary species! so one has to check for every variable id what object it is and if it is a species if the boundaryCondition is True). In addition the subsequent updates with `resetAll` are confusing, because A2 should be reset to the original value if it was not set via an `init` expression.

```
# Loading model and simulating
model = roadrunner.RoadRunner("boundary_condition.xml")  # type: roadrunner.ExecutableModel
model.selections = ["time", "A1", "A2", "[A1]", "[A2]"]

# default simulation
s = model.simulate()
s = pd.DataFrame(s, columns=s.colnames)
print(s.head(5))

print("-" * 80)
# setting initial value on species with "boundaryCondition=False"
model["init(A1)"] = 1000.0
# setting value on species with "boundaryCondition=True" (without init !)
model["A2"] = 1000.0
s = model.simulate()
s = pd.DataFrame(s, columns=s.colnames)
print(s.head(5))

print("-" * 80)
# here no reset of A2 despite not set via an init
model.resetAll()
s = model.simulate()
s = pd.DataFrame(s, columns=s.colnames)
print(s.head(5))
```

```
   time   A1   A2  [A1]  [A2]
0   0.0  1.0  1.0   0.5   0.5
1   0.1  1.0  1.0   0.5   0.5
2   0.2  1.0  1.0   0.5   0.5
3   0.3  1.0  1.0   0.5   0.5
4   0.4  1.0  1.0   0.5   0.5
--------------------------------------------------------------------------------
   time      A1      A2   [A1]   [A2]
0   0.0  1000.0  1000.0  500.0  500.0
1   0.1  1000.0  1000.0  500.0  500.0
2   0.2  1000.0  1000.0  500.0  500.0
3   0.3  1000.0  1000.0  500.0  500.0
4   0.4  1000.0  1000.0  500.0  500.0
--------------------------------------------------------------------------------
   time      A1      A2   [A1]   [A2]
0   0.0  1000.0  1000.0  500.0  500.0
1   0.1  1000.0  1000.0  500.0  500.0
2   0.2  1000.0  1000.0  500.0  500.0
3   0.3  1000.0  1000.0  500.0  500.0
4   0.4  1000.0  1000.0  500.0  500.0
```

**Comment by luciansmith** [comment]
This is now possible!  https://github.com/sys-bio/roadrunner/pull/812

The 'resetAll' function still needs work (https://github.com/sys-bio/roadrunner/issues/811) but getting and setting the initial value of a boundary species is now implemented.  This turned out to be a fundamental omission in the bowels of the code:  space was reserved for these values, but the host of functions necessary to get and set them were simply missing.  But they're there now!
