### ISSUE TITLE
Error when copying instances twice 

### ISSUE THREAD

**Issue by Scriptkiddi** [sys-bio/roadrunner#978]
I'm currently working on checkpointing a roadrunner instance. I encountered the problem, where when I execute the same script it exits with different errors even though this should definitely not happen.
Any ideas where this is coming from?
```python
import roadrunner
from copy import deepcopy

time = 0
#if model_state is None:
rr = roadrunner.RoadRunner("brusselator.xml")
print("test 1")
test = rr.__getstate__()
rr.__setstate__(test)
print("test 2")
test = rr.__getstate__()
rr.__setstate__(test)
print("test 3")
test = rr.__getstate__()
rr.__setstate__(test)
print("test 4")
test = rr.__getstate__()
rr.__setstate__(test)
print("test 5")
test = rr.__getstate__()
rr.__setstate__(test)
```
```
master $ python rr_test.py
test 1
test 2
Error: Failed to load object data
Failed to load object dataThe file was not recognized as a valid object file
[1]    1713337 segmentation fault (core dumped)  python rr_test.py
python rr_test.py 0.22s user 0.05s system 51% cpu 0.520 total
```
```
master $ python rr_test.py
test 1
test 2
Error: Failed to load object data
Failed to load object dataThe file was not recognized as a valid object file
^[[A[1]    1713365 segmentation fault (core dumped)  python rr_test.py
python rr_test.py 0.24s user 0.05s system 52% cpu 0.558 total
```
```
master $ python rr_test.py
test 1
test 2
test 3
Error: Unable to convert module to string. Have you made a call to addModule or addObject yet?
Traceback (most recent call last):
  File "rr_test.py", line 14, in <module>
    test = rr.__getstate__()
  File "/nix/store/r073v7wpmz23mqk1y5pls1611mn0dzfc-python3.9-roadrunner-python-2.2.0/lib/python3.9/site-packages/roadrunner/roadrunner.py", line 4394, in __getstate__
    return self.saveStateS()
  File "/nix/store/r073v7wpmz23mqk1y5pls1611mn0dzfc-python3.9-roadrunner-python-2.2.0/lib/python3.9/site-packages/roadrunner/roadrunner.py", line 3004, in saveStateS
    return _roadrunner.RoadRunner_saveStateS(self, *args, **kwargs)
RuntimeError: Unable to convert module to string. Have you made a call to addModule or addObject yet?, at virtual std::string rrllvm::MCJit::getModuleAsString(std::string)
[1]    1713408 exit 1     python rr_test.py
```

**Comment by Scriptkiddi** [comment]
Stack trace for a Failed to load data error
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x8)
==== backtrace (tid:1732847) ====
 0 0x0000000000012ee0 __funlockfile()  ???:0
 1 0x0000000002cb3350 llvm::RuntimeDyld::loadObject()  ???:0
 2 0x0000000002bf52eb llvm::MCJIT::addObjectFile()  ???:0
 3 0x0000000002bf25ea llvm::MCJIT::addObjectFile()  ???:0
 4 0x000000000077039c rrllvm::MCJit::addObjectFile()  ???:0
 5 0x0000000000743520 rrllvm::ModelResources::loadState()  ???:0
 6 0x00000000006e7e7f rrllvm::LLVMExecutableModel::LLVMExecutableModel()  ???:0
 7 0x00000000006ab5e6 rr::ExecutableModelFactory::createModel()  ???:0
 8 0x0000000000658913 rr::RoadRunner::loadStateS()  ???:0
 9 0x00000000005eb53f _wrap_RoadRunner_loadStateS()  ???:0
10 0x0000000000105a73 cfunction_call()  ???:0
11 0x00000000000b49c0 _PyObject_MakeTpCall.localalias()  ???:0
12 0x0000000000070a35 _PyEval_EvalFrameDefault()  ???:0
13 0x0000000000069413 function_code_fastcall()  ???:0
14 0x00000000000befa8 method_vectorcall()  ???:0
15 0x00000000000702fa _PyEval_EvalFrameDefault()  ???:0
16 0x0000000000069413 function_code_fastcall()  ???:0
17 0x00000000000befa8 method_vectorcall()  ???:0
18 0x0000000000007a0d _Pickle_FastCall()  ???:0
19 0x000000000000c8a9 load_build.isra.0()  ???:0
20 0x000000000000dd31 load()  ???:0
21 0x000000000000fa13 _pickle_loads()  ???:0
22 0x00000000000bdfc9 cfunction_vectorcall_FASTCALL_KEYWORDS()  ???:0
23 0x00000000000702fa _PyEval_EvalFrameDefault()  ???:0
24 0x00000000001b5d9c _PyEval_EvalCode()  ???:0
25 0x00000000001b619e _PyFunction_Vectorcall()  ???:0
26 0x0000000000070235 _PyEval_EvalFrameDefault()  ???:0
27 0x00000000001b5d9c _PyEval_EvalCode()  ???:0
28 0x00000000001b634d PyEval_EvalCode()  ???:0
29 0x000000000027a525 run_mod()  ???:0
30 0x000000000028cfdd PyRun_SimpleFileExFlags.localalias()  ???:0
31 0x000000000028e47b Py_RunMain.localalias()  ???:0
32 0x000000000028eac0 Py_BytesMain()  ???:0
33 0x0000000000027790 __libc_start_main()  ???:0
34 0x000000000040107a _start()  ???:0

```

**Comment by Scriptkiddi** [comment]
https://github.com/sys-bio/roadrunner/issues/976

**Comment by Scriptkiddi** [comment]
`roadrunner.Config.setValue(roadrunner.Config.LLVM_BACKEND, roadrunner.Config.LLJIT)`

**Comment by luciansmith** [comment]
As you noticed, I think your problem is the same as was found in #976.  We found a solution that has been implemented, and should be incorporated into the next release, which should work even if you use the default MCJit instead of switching to LLJit.  LLJit is faster, though, so as long as you don't run into any other issues with it, feel free to keep using it!
